pandas를 이용할 때 가장 기본적인 새로운 행과 열을 삽입하는 방법에 대해서 배워보겠습니다.

In [8]:
import pandas as pd

data = [[-4, -3, -2, -1],[1,2,3,4]]
data2 = [5,6,7,8]
data3 = [9,10,11,12]

#list 이용하기
data_list = []
data_list.append(data)
# print(data_list)

data_list.append(data2)
# print(data_list)

data_list.insert(0,data3)
# print(data_list)


df = pd.DataFrame(data, columns=['A','B','C','D'])
# print(df)

temp_df = pd.DataFrame([data2],columns=['A','B','C','D'])
df = pd.concat([df,temp_df]).reset_index(drop=True)
# print(df)

#pandas 새로운 column 추가하기
sz = len(df)
data2 = [i * 100 for i in range(sz)]
# i*100을 채우기
# for i in range(sz)가 완료할때까지
temp = pd.Series(data2, name='colAdd')
df = df.join(temp)
# print(df)

   A  B  C  D  colAdd
0 -4 -3 -2 -1       0
1  1  2  3  4     100
2  5  6  7  8     200


pandas 정렬과 index 갱신하는 방법

In [17]:
import pandas as pd
import numpy as np

data1 = [12000,11590, 13110, 14000]
data2 = [20151015,20151015,20151014,20151014]
data3 = [1000,901,902,1400]
data = [data1,data2,data3]
print('data: ', data,'\n\n')

newData = np.transpose(data)
print('transposed data: \n', newData,'\n\n')

df = pd.DataFrame(newData, columns=['Close','Date','Time'])
print('DataFrame: \n',df,'\n\n')

df = df.sort_values(['Date','Time'],ascending=[True,True])
print('sorted data: \n', df,'\n\n')

df = df.reset_index(drop=True)
print('re indexed data: \n', df)

data:  [[12000, 11590, 13110, 14000], [20151015, 20151015, 20151014, 20151014], [1000, 901, 902, 1400]] 


transposed data: 
 [[   12000 20151015     1000]
 [   11590 20151015      901]
 [   13110 20151014      902]
 [   14000 20151014     1400]] 


DataFrame: 
    Close      Date  Time
0  12000  20151015  1000
1  11590  20151015   901
2  13110  20151014   902
3  14000  20151014  1400 


sorted data: 
    Close      Date  Time
2  13110  20151014   902
3  14000  20151014  1400
1  11590  20151015   901
0  12000  20151015  1000 


re indexed data: 
    Close      Date  Time
0  13110  20151014   902
1  14000  20151014  1400
2  11590  20151015   901
3  12000  20151015  1000


In [20]:
#pandas indexing
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(7,2), index=range(0,21,3),columns=list(['A','B']))

print(df)
print(df.loc[6])
print(df.iloc[6])

           A         B
0  -1.662612  0.040898
3  -0.069007  0.114094
6   1.076389  0.391915
9   0.094702 -0.170226
12  0.398801  0.852634
15  1.137965  0.672560
18  0.505033  1.769586
A    1.076389
B    0.391915
Name: 6, dtype: float64
A    0.505033
B    1.769586
Name: 18, dtype: float64


In [22]:
df = pd.DataFrame(np.arange(16).reshape(4,4), index=['5월','6월','7월','8월'],columns=[['kospi','kospi','kosdaq','kosdaq'],['price','qty','price','qty']])
print(df)

   kospi     kosdaq    
   price qty  price qty
5월     0   1      2   3
6월     4   5      6   7
7월     8   9     10  11
8월    12  13     14  15
